package org.packt.online.cart.portal.model.data;

// Generated 11 1, 15 3:03:23 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BillingStatement generated by hbm2java
 */
@Entity
@Table(name = "billing_statement", catalog = "ocs")
public class BillingStatement implements java.io.Serializable {

	private Integer id;
	private BillingAddress billingAddress;
	private int catalogId;
	private int qty;
	private BigDecimal total;
	private Set<OrderPayment> orderPayments = new HashSet<OrderPayment>(0);

	public BillingStatement() {
	}

	public BillingStatement(BillingAddress billingAddress, int catalogId,
			int qty, BigDecimal total) {
		this.billingAddress = billingAddress;
		this.catalogId = catalogId;
		this.qty = qty;
		this.total = total;
	}

	public BillingStatement(BillingAddress billingAddress, int catalogId,
			int qty, BigDecimal total, Set<OrderPayment> orderPayments) {
		this.billingAddress = billingAddress;
		this.catalogId = catalogId;
		this.qty = qty;
		this.total = total;
		this.orderPayments = orderPayments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "transId", nullable = false)
	public BillingAddress getBillingAddress() {
		return this.billingAddress;
	}

	public void setBillingAddress(BillingAddress billingAddress) {
		this.billingAddress = billingAddress;
	}

	@Column(name = "catalogId", nullable = false)
	public int getCatalogId() {
		return this.catalogId;
	}

	public void setCatalogId(int catalogId) {
		this.catalogId = catalogId;
	}

	@Column(name = "qty", nullable = false)
	public int getQty() {
		return this.qty;
	}

	public void setQty(int qty) {
		this.qty = qty;
	}

	@Column(name = "total", nullable = false, precision = 10)
	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "billingStatement")
	public Set<OrderPayment> getOrderPayments() {
		return this.orderPayments;
	}

	public void setOrderPayments(Set<OrderPayment> orderPayments) {
		this.orderPayments = orderPayments;
	}

}
