package org.packt.online.cart.portal.model.data;

// Generated 11 1, 15 3:03:23 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * CustomerAccount generated by hbm2java
 */

@Entity
@Table(name = "customer_account", catalog = "ocs")
public class CustomerAccount implements java.io.Serializable {

	private Integer id;
	private String firstName;
	private String midName;
	private String lastName;
	private Date birthDate;
	private String address;
	private String email;
	private String mobile;
	private Date startDate;
	private String username;
	private Login login;
	private Set<ShipmentDetails> shipmentDetailses = new HashSet<ShipmentDetails>(
			0);
	private Set<BillingAddress> billingAddresses = new HashSet<BillingAddress>(
			0);

	public CustomerAccount() {
	}

	public CustomerAccount(String firstName, String midName, String lastName,
			Date birthDate, String address, String email, String mobile,
			Date startDate, String username) {
		this.firstName = firstName;
		this.midName = midName;
		this.lastName = lastName;
		this.birthDate = birthDate;
		this.address = address;
		this.email = email;
		this.mobile = mobile;
		this.startDate = startDate;
		this.username = username;
	}

	public CustomerAccount(String firstName, String midName, String lastName,
			Date birthDate, String address, String email, String mobile,
			Date startDate, String username, Login login,
			Set<ShipmentDetails> shipmentDetailses,
			Set<BillingAddress> billingAddresses) {
		this.firstName = firstName;
		this.midName = midName;
		this.lastName = lastName;
		this.birthDate = birthDate;
		this.address = address;
		this.email = email;
		this.mobile = mobile;
		this.startDate = startDate;
		this.username = username;
		this.login = login;
		this.shipmentDetailses = shipmentDetailses;
		this.billingAddresses = billingAddresses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "firstName", nullable = false, length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "midName", nullable = false, length = 45)
	public String getMidName() {
		return this.midName;
	}

	public void setMidName(String midName) {
		this.midName = midName;
	}

	@Column(name = "lastName", nullable = false, length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthDate", nullable = false, length = 10)
	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	@Column(name = "address", nullable = false, length = 45)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "email", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "mobile", nullable = false, length = 45)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "startDate", nullable = false, length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "username", nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "customerAccount")
	public Login getLogin() {
		return this.login;
	}

	public void setLogin(Login login) {
		this.login = login;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerAccount")
	public Set<ShipmentDetails> getShipmentDetailses() {
		return this.shipmentDetailses;
	}

	public void setShipmentDetailses(Set<ShipmentDetails> shipmentDetailses) {
		this.shipmentDetailses = shipmentDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerAccount")
	public Set<BillingAddress> getBillingAddresses() {
		return this.billingAddresses;
	}

	public void setBillingAddresses(Set<BillingAddress> billingAddresses) {
		this.billingAddresses = billingAddresses;
	}

}
