
package org.packt.erp.modules.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SalesInventoryServiceImplService", targetNamespace = "http://impl.service.modules.erp.packt.org/", wsdlLocation = "http://localhost:8080/ch08/sales-inventory-dao?wsdl")
public class SalesInventoryServiceImplService
    extends Service
{

    private final static URL SALESINVENTORYSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SALESINVENTORYSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName SALESINVENTORYSERVICEIMPLSERVICE_QNAME = new QName("http://impl.service.modules.erp.packt.org/", "SalesInventoryServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ch08/sales-inventory-dao?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SALESINVENTORYSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        SALESINVENTORYSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public SalesInventoryServiceImplService() {
        super(__getWsdlLocation(), SALESINVENTORYSERVICEIMPLSERVICE_QNAME);
    }

    public SalesInventoryServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SALESINVENTORYSERVICEIMPLSERVICE_QNAME, features);
    }

    public SalesInventoryServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SALESINVENTORYSERVICEIMPLSERVICE_QNAME);
    }

    public SalesInventoryServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SALESINVENTORYSERVICEIMPLSERVICE_QNAME, features);
    }

    public SalesInventoryServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SalesInventoryServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SalesInventoryServiceImpl
     */
    @WebEndpoint(name = "SalesInventoryServiceImplPort")
    public SalesInventoryServiceImpl getSalesInventoryServiceImplPort() {
        return super.getPort(new QName("http://impl.service.modules.erp.packt.org/", "SalesInventoryServiceImplPort"), SalesInventoryServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SalesInventoryServiceImpl
     */
    @WebEndpoint(name = "SalesInventoryServiceImplPort")
    public SalesInventoryServiceImpl getSalesInventoryServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.modules.erp.packt.org/", "SalesInventoryServiceImplPort"), SalesInventoryServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SALESINVENTORYSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw SALESINVENTORYSERVICEIMPLSERVICE_EXCEPTION;
        }
        return SALESINVENTORYSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
