
package org.packt.erp.modules.service.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SalesInventoryServiceImpl", targetNamespace = "http://impl.service.modules.erp.packt.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SalesInventoryServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns org.packt.erp.modules.service.impl.Contact
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getContactInfo", targetNamespace = "http://impl.service.modules.erp.packt.org/", className = "org.packt.erp.modules.service.impl.GetContactInfo")
    @ResponseWrapper(localName = "getContactInfoResponse", targetNamespace = "http://impl.service.modules.erp.packt.org/", className = "org.packt.erp.modules.service.impl.GetContactInfoResponse")
    @Action(input = "http://impl.service.modules.erp.packt.org/SalesInventoryServiceImpl/getContactInfoRequest", output = "http://impl.service.modules.erp.packt.org/SalesInventoryServiceImpl/getContactInfoResponse")
    public Contact getContactInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @return
     *     returns java.util.List<org.packt.erp.modules.service.impl.Supplier>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllSuppliers", targetNamespace = "http://impl.service.modules.erp.packt.org/", className = "org.packt.erp.modules.service.impl.GetAllSuppliers")
    @ResponseWrapper(localName = "getAllSuppliersResponse", targetNamespace = "http://impl.service.modules.erp.packt.org/", className = "org.packt.erp.modules.service.impl.GetAllSuppliersResponse")
    @Action(input = "http://impl.service.modules.erp.packt.org/SalesInventoryServiceImpl/getAllSuppliersRequest", output = "http://impl.service.modules.erp.packt.org/SalesInventoryServiceImpl/getAllSuppliersResponse")
    public List<Supplier> getAllSuppliers();

}
