package org.packt.hotel.portal.model.data;
// Generated 09 19, 15 12:25:43 AM by Hibernate Tools 4.3.1

/**
 * HmsLogin generated by hbm2java
 */
public class HmsLogin implements java.io.Serializable {

	private Integer id;
	private String username;
	private String password;
	private HmsUserProfile hmsUserProfile;

	
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public HmsUserProfile getHmsUserProfile() {
		return this.hmsUserProfile;
	}

	public void setHmsUserProfile(HmsUserProfile hmsUserProfile) {
		this.hmsUserProfile = hmsUserProfile;
	}

}
