package org.packt.hotel.portal.model.data;
// Generated 09 19, 15 12:25:43 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * HmsMenuBooking generated by hbm2java
 */
public class HmsMenuBooking implements java.io.Serializable {

	private Integer id;
	private HmsMenu hmsMenu;
	private int bookId;
	private Set<HmsRoomBooking> hmsRoomBookings = new HashSet<HmsRoomBooking>(0);

	
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public HmsMenu getHmsMenu() {
		return this.hmsMenu;
	}

	public void setHmsMenu(HmsMenu hmsMenu) {
		this.hmsMenu = hmsMenu;
	}

	public int getBookId() {
		return this.bookId;
	}

	public void setBookId(int bookId) {
		this.bookId = bookId;
	}

	public Set<HmsRoomBooking> getHmsRoomBookings() {
		return this.hmsRoomBookings;
	}

	public void setHmsRoomBookings(Set<HmsRoomBooking> hmsRoomBookings) {
		this.hmsRoomBookings = hmsRoomBookings;
	}

}
