package org.packt.hotel.portal.model.data;
// Generated 09 19, 15 12:25:43 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * HmsMenu generated by hbm2java
 */
public class HmsMenu implements java.io.Serializable {

	private Integer id;
	private Date menuDate;
	private String menuName;
	private String menuPlan;
	private int qty;
	private double price;
	private Set<HmsMenuBooking> hmsMenuBookings = new HashSet<HmsMenuBooking>(0);

	
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getMenuDate() {
		return this.menuDate;
	}

	public void setMenuDate(Date menuDate) {
		this.menuDate = menuDate;
	}

	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	public String getMenuPlan() {
		return this.menuPlan;
	}

	public void setMenuPlan(String menuPlan) {
		this.menuPlan = menuPlan;
	}

	public int getQty() {
		return this.qty;
	}

	public void setQty(int qty) {
		this.qty = qty;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public Set<HmsMenuBooking> getHmsMenuBookings() {
		return this.hmsMenuBookings;
	}

	public void setHmsMenuBookings(Set<HmsMenuBooking> hmsMenuBookings) {
		this.hmsMenuBookings = hmsMenuBookings;
	}

}
