package org.packt.hotel.portal.model.data;
// Generated 09 19, 15 12:25:43 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * HmsRoomBooking generated by hbm2java
 */
public class HmsRoomBooking implements java.io.Serializable {

	private Integer id;
	private HmsMenuBooking hmsMenuBooking;
	private HmsRoomsMasterlist hmsRoomsMasterlist;
	private HmsUserProfile hmsUserProfile;
	private Date bookingDate;
	private String bookingStatus;

	

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public HmsMenuBooking getHmsMenuBooking() {
		return this.hmsMenuBooking;
	}

	public void setHmsMenuBooking(HmsMenuBooking hmsMenuBooking) {
		this.hmsMenuBooking = hmsMenuBooking;
	}

	public HmsRoomsMasterlist getHmsRoomsMasterlist() {
		return this.hmsRoomsMasterlist;
	}

	public void setHmsRoomsMasterlist(HmsRoomsMasterlist hmsRoomsMasterlist) {
		this.hmsRoomsMasterlist = hmsRoomsMasterlist;
	}

	public HmsUserProfile getHmsUserProfile() {
		return this.hmsUserProfile;
	}

	public void setHmsUserProfile(HmsUserProfile hmsUserProfile) {
		this.hmsUserProfile = hmsUserProfile;
	}

	public Date getBookingDate() {
		return this.bookingDate;
	}

	public void setBookingDate(Date bookingDate) {
		this.bookingDate = bookingDate;
	}

	public String getBookingStatus() {
		return this.bookingStatus;
	}

	public void setBookingStatus(String bookingStatus) {
		this.bookingStatus = bookingStatus;
	}

}
