package org.packt.hotel.portal.model.data;
// Generated 09 19, 15 12:25:43 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * HmsUserProfile generated by hbm2java
 */
public class HmsUserProfile implements java.io.Serializable {

	private int id;
	private HmsLogin hmsLogin;
	private String firstName;
	private String lastName;
	private String address;
	private String mobile;
	private String email;
	private Set<HmsRoomBooking> hmsRoomBookings = new HashSet<HmsRoomBooking>(0);

	

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public HmsLogin getHmsLogin() {
		return this.hmsLogin;
	}

	public void setHmsLogin(HmsLogin hmsLogin) {
		this.hmsLogin = hmsLogin;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set<HmsRoomBooking> getHmsRoomBookings() {
		return this.hmsRoomBookings;
	}

	public void setHmsRoomBookings(Set<HmsRoomBooking> hmsRoomBookings) {
		this.hmsRoomBookings = hmsRoomBookings;
	}

}
