package org.packt.hotel.portal.model.data;
// Generated 09 19, 15 12:25:43 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Status generated by hbm2java
 */
public class Status implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<HmsRoomsMasterlist> hmsRoomsMasterlists = new HashSet<HmsRoomsMasterlist>(0);

	

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<HmsRoomsMasterlist> getHmsRoomsMasterlists() {
		return this.hmsRoomsMasterlists;
	}

	public void setHmsRoomsMasterlists(Set<HmsRoomsMasterlist> hmsRoomsMasterlists) {
		this.hmsRoomsMasterlists = hmsRoomsMasterlists;
	}

}
