package org.packt.academic.student.portal.model.data;

// Generated 10 3, 15 11:23:41 AM by Hibernate Tools 4.3.1


/**
 * Level generated by hbm2java
 */
public class Level implements java.io.Serializable  {

	private int level;
	private String label;
	

	public int getLevel() {
		return this.level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	
}
