package org.packt.academic.student.portal.model.data;

// Generated 03 9, 16 11:21:43 PM by Hibernate Tools 3.4.0.CR1

/**
 * Tblstudentgrades generated by hbm2java
 */
public class Tblstudentgrades implements java.io.Serializable {

	private Integer id;
	private Tblcourses tblcourses;
	private Tblstudents tblstudents;
	private double grade;
	private int semester;
	private int level;
	private int facultyId;

	public Tblstudentgrades() {
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Tblcourses getTblcourses() {
		return this.tblcourses;
	}

	public void setTblcourses(Tblcourses tblcourses) {
		this.tblcourses = tblcourses;
	}

	public Tblstudents getTblstudents() {
		return this.tblstudents;
	}

	public void setTblstudents(Tblstudents tblstudents) {
		this.tblstudents = tblstudents;
	}

	public double getGrade() {
		return this.grade;
	}

	public void setGrade(double grade) {
		this.grade = grade;
	}

	public int getSemester() {
		return this.semester;
	}

	public void setSemester(int semester) {
		this.semester = semester;
	}

	public int getLevel() {
		return this.level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	public int getFacultyId() {
		return this.facultyId;
	}

	public void setFacultyId(int facultyId) {
		this.facultyId = facultyId;
	}

}
