//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.27 at 11:00:08 AM CST 
//


package org.packt.erp.modules.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="invoicedProduct" type="{http://invprod.packt.erp.modules.org}InvoicedProducts"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "invoicedProduct"
})
@XmlRootElement(name = "InvoiceProductSaveRequest", namespace = "http://invprod.packt.erp.modules.org/setInvoicedProduct")
public class InvoiceProductSaveRequest {

    @XmlElement(namespace = "http://invprod.packt.erp.modules.org/setInvoicedProduct", required = true)
    protected InvoicedProducts invoicedProduct;

    /**
     * Gets the value of the invoicedProduct property.
     * 
     * @return
     *     possible object is
     *     {@link InvoicedProducts }
     *     
     */
    public InvoicedProducts getInvoicedProduct() {
        return invoicedProduct;
    }

    /**
     * Sets the value of the invoicedProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoicedProducts }
     *     
     */
    public void setInvoicedProduct(InvoicedProducts value) {
        this.invoicedProduct = value;
    }

}
