
package org.packt.erp.modules;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MyWebService", targetNamespace = "http://modules.erp.packt.org/", wsdlLocation = "http://localhost:8080/ch08/jaxws-spring?wsdl")
public class MyWebService_Service
    extends Service
{

    private final static URL MYWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException MYWEBSERVICE_EXCEPTION;
    private final static QName MYWEBSERVICE_QNAME = new QName("http://modules.erp.packt.org/", "MyWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ch08/jaxws-spring?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MYWEBSERVICE_WSDL_LOCATION = url;
        MYWEBSERVICE_EXCEPTION = e;
    }

    public MyWebService_Service() {
        super(__getWsdlLocation(), MYWEBSERVICE_QNAME);
    }

    public MyWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), MYWEBSERVICE_QNAME, features);
    }

    public MyWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, MYWEBSERVICE_QNAME);
    }

    public MyWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MYWEBSERVICE_QNAME, features);
    }

    public MyWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MyWebService
     */
    @WebEndpoint(name = "MyWebServicePort")
    public MyWebService getMyWebServicePort() {
        return super.getPort(new QName("http://modules.erp.packt.org/", "MyWebServicePort"), MyWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyWebService
     */
    @WebEndpoint(name = "MyWebServicePort")
    public MyWebService getMyWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://modules.erp.packt.org/", "MyWebServicePort"), MyWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MYWEBSERVICE_EXCEPTION!= null) {
            throw MYWEBSERVICE_EXCEPTION;
        }
        return MYWEBSERVICE_WSDL_LOCATION;
    }

}
