//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.18 at 07:33:42 PM CST 
//


package org.packt.erp.modules.ws;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.packt.erp.modules.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.packt.erp.modules.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InvoiceProductSaveRequest }
     * 
     */
    public InvoiceProductSaveRequest createInvoiceProductSaveRequest() {
        return new InvoiceProductSaveRequest();
    }

    /**
     * Create an instance of {@link InvoicedProducts }
     * 
     */
    public InvoicedProducts createInvoicedProducts() {
        return new InvoicedProducts();
    }

    /**
     * Create an instance of {@link InvoiceProductSaveResponse }
     * 
     */
    public InvoiceProductSaveResponse createInvoiceProductSaveResponse() {
        return new InvoiceProductSaveResponse();
    }

    /**
     * Create an instance of {@link Invoice }
     * 
     */
    public Invoice createInvoice() {
        return new Invoice();
    }

    /**
     * Create an instance of {@link PaymentAp }
     * 
     */
    public PaymentAp createPaymentAp() {
        return new PaymentAp();
    }

    /**
     * Create an instance of {@link InvoiceProductsResponse }
     * 
     */
    public InvoiceProductsResponse createInvoiceProductsResponse() {
        return new InvoiceProductsResponse();
    }

    /**
     * Create an instance of {@link InvoiceProductRequest }
     * 
     */
    public InvoiceProductRequest createInvoiceProductRequest() {
        return new InvoiceProductRequest();
    }

    /**
     * Create an instance of {@link InvoiceProductResponse }
     * 
     */
    public InvoiceProductResponse createInvoiceProductResponse() {
        return new InvoiceProductResponse();
    }

}
