//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.18 at 07:33:42 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://invprod.packt.erp.modules.org", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.packt.erp.modules.ws;
