package org.packt.bus.portal.model.data;

// Generated 01 1, 16 4:39:20 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BookingPayment generated by hbm2java
 */
@Entity
@Table(name = "booking_payment", catalog = "bts")
public class BookingPayment implements java.io.Serializable {

	private int id;
	private BookedTrip bookedTrip;
	private String mode;
	private String status;

	public BookingPayment() {
	}

	public BookingPayment(int id, BookedTrip bookedTrip, String mode,
			String status) {
		this.id = id;
		this.bookedTrip = bookedTrip;
		this.mode = mode;
		this.status = status;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bookingId", nullable = false)
	public BookedTrip getBookedTrip() {
		return this.bookedTrip;
	}

	public void setBookedTrip(BookedTrip bookedTrip) {
		this.bookedTrip = bookedTrip;
	}

	@Column(name = "mode", nullable = false, length = 45)
	public String getMode() {
		return this.mode;
	}

	public void setMode(String mode) {
		this.mode = mode;
	}

	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
