package org.packt.bus.portal.model.data;

// Generated 01 1, 16 4:39:20 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * BookedTrip generated by hbm2java
 */
@Entity
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
@Table(name = "booked_trip", catalog = "bts")
public class BookedTrip implements java.io.Serializable {

	private int id;
	private CustomerInfo customerInfo;
	private Trip trip;
	private int adults;
	private int kids;
	private Date booked;
	private String status;
	private double total;
	
	@XmlTransient
	private Set<BookingPayment> bookingPayments = new HashSet<BookingPayment>(0);

	public BookedTrip() {
	}

	public BookedTrip(int id, CustomerInfo customerInfo, Trip trip, int adults,
			int kids, Date booked, String status, double total) {
		this.id = id;
		this.customerInfo = customerInfo;
		this.trip = trip;
		this.adults = adults;
		this.kids = kids;
		this.booked = booked;
		this.status = status;
		this.total = total;
	}

	public BookedTrip(int id, CustomerInfo customerInfo, Trip trip, int adults,
			int kids, Date booked, String status, double total,
			Set<BookingPayment> bookingPayments) {
		this.id = id;
		this.customerInfo = customerInfo;
		this.trip = trip;
		this.adults = adults;
		this.kids = kids;
		this.booked = booked;
		this.status = status;
		this.total = total;
		this.bookingPayments = bookingPayments;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	@JsonManagedReference("customer-data")
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId", nullable = false)
	public CustomerInfo getCustomerInfo() {
		return this.customerInfo;
	}

	public void setCustomerInfo(CustomerInfo customerInfo) {
		this.customerInfo = customerInfo;
	}

	@JsonManagedReference("booked-data")
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tripId", nullable = false)
	public Trip getTrip() {
		return this.trip;
	}

	public void setTrip(Trip trip) {
		this.trip = trip;
	}

	@Column(name = "adults", nullable = false)
	public int getAdults() {
		return this.adults;
	}

	public void setAdults(int adults) {
		this.adults = adults;
	}

	@Column(name = "kids", nullable = false)
	public int getKids() {
		return this.kids;
	}

	public void setKids(int kids) {
		this.kids = kids;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "booked", nullable = false, length = 10)
	public Date getBooked() {
		return this.booked;
	}

	public void setBooked(Date booked) {
		this.booked = booked;
	}

	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "total", nullable = false, precision = 22, scale = 0)
	public double getTotal() {
		return this.total;
	}

	public void setTotal(double total) {
		this.total = total;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bookedTrip")
	public Set<BookingPayment> getBookingPayments() {
		return this.bookingPayments;
	}

	public void setBookingPayments(Set<BookingPayment> bookingPayments) {
		this.bookingPayments = bookingPayments;
	}

}
