package org.packt.bus.portal.model.data;

// Generated 01 1, 16 4:39:20 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * CustomerInfo generated by hbm2java
 */
@Entity
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
@Table(name = "customer_info", catalog = "bts")
public class CustomerInfo implements java.io.Serializable {

	private int id;
	private String firstName;
	private String middleName;
	private String lastName;
	private int age;
	@XmlTransient
	private Set<BookedTrip> bookedTrips = new HashSet<BookedTrip>(0);
	private Login login;

	public CustomerInfo() {
	}

	public CustomerInfo(int id, String firstName, String middleName,
			String lastName, int age) {
		this.id = id;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.age = age;
	}

	public CustomerInfo(int id, String firstName, String middleName,
			String lastName, int age, Set<BookedTrip> bookedTrips, Login login) {
		this.id = id;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.age = age;
		this.bookedTrips = bookedTrips;
		this.login = login;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "firstName", nullable = false, length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "middleName", nullable = false, length = 45)
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "lastName", nullable = false, length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "age", nullable = false)
	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	@JsonBackReference("customer-data")
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerInfo")
	public Set<BookedTrip> getBookedTrips() {
		return this.bookedTrips;
	}

	public void setBookedTrips(Set<BookedTrip> bookedTrips) {
		this.bookedTrips = bookedTrips;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "customerInfo")
	public Login getLogin() {
		return this.login;
	}

	public void setLogin(Login login) {
		this.login = login;
	}

}
