package org.packt.bus.portal.model.data;

// Generated 01 1, 16 4:39:20 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonManagedReference;

import javax.xml.bind.annotation.XmlAccessType;

/**
 * Trip generated by hbm2java
 */
@Entity
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
@Table(name = "trip", catalog = "bts")
public class Trip implements java.io.Serializable {

	private int id;
	private StationDetail stationDetail;
	private String name;
	private int sightsStops;
	private int dayDuration;
	private int nightDuration;
	private String typeDuration;
	private String otherTransport;
	private String language;
	private double priceAdult;
	private double priceKid;
	
	@XmlTransient
	private Set<BookedTrip> bookedTrips = new HashSet<BookedTrip>(0);

	public Trip() {
	}

	public Trip(int id, StationDetail stationDetail, String name,
			int sightsStops, int dayDuration, int nightDuration,
			String typeDuration, String otherTransport, String language,
			double priceAdult, double priceKid) {
		this.id = id;
		this.stationDetail = stationDetail;
		this.name = name;
		this.sightsStops = sightsStops;
		this.dayDuration = dayDuration;
		this.nightDuration = nightDuration;
		this.typeDuration = typeDuration;
		this.otherTransport = otherTransport;
		this.language = language;
		this.priceAdult = priceAdult;
		this.priceKid = priceKid;
	}

	public Trip(int id, StationDetail stationDetail, String name,
			int sightsStops, int dayDuration, int nightDuration,
			String typeDuration, String otherTransport, String language,
			double priceAdult, double priceKid, Set<BookedTrip> bookedTrips) {
		this.id = id;
		this.stationDetail = stationDetail;
		this.name = name;
		this.sightsStops = sightsStops;
		this.dayDuration = dayDuration;
		this.nightDuration = nightDuration;
		this.typeDuration = typeDuration;
		this.otherTransport = otherTransport;
		this.language = language;
		this.priceAdult = priceAdult;
		this.priceKid = priceKid;
		this.bookedTrips = bookedTrips;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@JsonBackReference("trips-data")
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stationId", nullable = false)
	public StationDetail getStationDetail() {
		return this.stationDetail;
	}

	public void setStationDetail(StationDetail stationDetail) {
		this.stationDetail = stationDetail;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "sights_stops", nullable = false)
	public int getSightsStops() {
		return this.sightsStops;
	}

	public void setSightsStops(int sightsStops) {
		this.sightsStops = sightsStops;
	}

	@Column(name = "day_duration", nullable = false)
	public int getDayDuration() {
		return this.dayDuration;
	}

	public void setDayDuration(int dayDuration) {
		this.dayDuration = dayDuration;
	}

	@Column(name = "night_duration", nullable = false)
	public int getNightDuration() {
		return this.nightDuration;
	}

	public void setNightDuration(int nightDuration) {
		this.nightDuration = nightDuration;
	}

	@Column(name = "type_duration", nullable = false, length = 45)
	public String getTypeDuration() {
		return this.typeDuration;
	}

	public void setTypeDuration(String typeDuration) {
		this.typeDuration = typeDuration;
	}

	@Column(name = "other_transport", nullable = false, length = 45)
	public String getOtherTransport() {
		return this.otherTransport;
	}

	public void setOtherTransport(String otherTransport) {
		this.otherTransport = otherTransport;
	}

	@Column(name = "language", nullable = false, length = 45)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Column(name = "price_adult", nullable = false, precision = 22, scale = 0)
	public double getPriceAdult() {
		return this.priceAdult;
	}

	public void setPriceAdult(double priceAdult) {
		this.priceAdult = priceAdult;
	}

	@Column(name = "price_kid", nullable = false, precision = 22, scale = 0)
	public double getPriceKid() {
		return this.priceKid;
	}

	public void setPriceKid(double priceKid) {
		this.priceKid = priceKid;
	}


	@JsonBackReference("booked-data")
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trip")
	public Set<BookedTrip> getBookedTrips() {
		return this.bookedTrips;
	}

	public void setBookedTrips(Set<BookedTrip> bookedTrips) {
		this.bookedTrips = bookedTrips;
	}

}
