package org.packt.human.resource.portal.model.data;
// Generated 08 7, 15 10:09:21 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HrmsEmployeeDetails generated by hbm2java
 */
@Entity
@Table(name = "hrms_employee_details", catalog = "hrms")
public class HrmsEmployeeDetails implements java.io.Serializable {

	private int empId;
	private Department department;
	private Positions positions;
	private String firstName;
	private String lastName;
	private String midName;
	private Date birthDate;
	private int age;
	private String sex;
	private String address;
	private Date employedDate;
	private int supervisorId;
	private Set<HrmsLogin> hrmsLogins = new HashSet<HrmsLogin>(0);
	private Set<HrmsEmployeeProjects> hrmsEmployeeProjectses = new HashSet<HrmsEmployeeProjects>(0);
	private Set<HrmsEmployeeTrainings> hrmsEmployeeTrainingses = new HashSet<HrmsEmployeeTrainings>(0);
	private Set<HrmsEmployeeLeaves> hrmsEmployeeLeaveses = new HashSet<HrmsEmployeeLeaves>(0);
	private Set<HrmsEmployeeSalary> hrmsEmployeeSalaries = new HashSet<HrmsEmployeeSalary>(0);
	private Set<HrmsEmployeeAttendance> hrmsEmployeeAttendances = new HashSet<HrmsEmployeeAttendance>(0);

	
	@Id

	@Column(name = "empId", unique = true, nullable = false)
	public int getEmpId() {
		return this.empId;
	}

	public void setEmpId(int empId) {
		this.empId = empId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "deptId", nullable = false)
	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "positionId", nullable = false)
	public Positions getPositions() {
		return this.positions;
	}

	public void setPositions(Positions positions) {
		this.positions = positions;
	}

	@Column(name = "firstName", nullable = false, length = 50)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "lastName", nullable = false, length = 50)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "midName", nullable = false, length = 50)
	public String getMidName() {
		return this.midName;
	}

	public void setMidName(String midName) {
		this.midName = midName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthDate", nullable = false, length = 10)
	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	@Column(name = "age", nullable = false)
	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	@Column(name = "sex", nullable = false, length = 2)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "address", nullable = false, length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "employedDate", nullable = false, length = 10)
	public Date getEmployedDate() {
		return this.employedDate;
	}

	public void setEmployedDate(Date employedDate) {
		this.employedDate = employedDate;
	}

	@Column(name = "supervisorId", nullable = false)
	public int getSupervisorId() {
		return this.supervisorId;
	}

	public void setSupervisorId(int supervisorId) {
		this.supervisorId = supervisorId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hrmsEmployeeDetails")
	public Set<HrmsLogin> getHrmsLogins() {
		return this.hrmsLogins;
	}

	public void setHrmsLogins(Set<HrmsLogin> hrmsLogins) {
		this.hrmsLogins = hrmsLogins;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hrmsEmployeeDetails")
	public Set<HrmsEmployeeProjects> getHrmsEmployeeProjectses() {
		return this.hrmsEmployeeProjectses;
	}

	public void setHrmsEmployeeProjectses(Set<HrmsEmployeeProjects> hrmsEmployeeProjectses) {
		this.hrmsEmployeeProjectses = hrmsEmployeeProjectses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hrmsEmployeeDetails")
	public Set<HrmsEmployeeTrainings> getHrmsEmployeeTrainingses() {
		return this.hrmsEmployeeTrainingses;
	}

	public void setHrmsEmployeeTrainingses(Set<HrmsEmployeeTrainings> hrmsEmployeeTrainingses) {
		this.hrmsEmployeeTrainingses = hrmsEmployeeTrainingses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hrmsEmployeeDetails")
	public Set<HrmsEmployeeLeaves> getHrmsEmployeeLeaveses() {
		return this.hrmsEmployeeLeaveses;
	}

	public void setHrmsEmployeeLeaveses(Set<HrmsEmployeeLeaves> hrmsEmployeeLeaveses) {
		this.hrmsEmployeeLeaveses = hrmsEmployeeLeaveses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hrmsEmployeeDetails")
	public Set<HrmsEmployeeSalary> getHrmsEmployeeSalaries() {
		return this.hrmsEmployeeSalaries;
	}

	public void setHrmsEmployeeSalaries(Set<HrmsEmployeeSalary> hrmsEmployeeSalaries) {
		this.hrmsEmployeeSalaries = hrmsEmployeeSalaries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hrmsEmployeeDetails")
	public Set<HrmsEmployeeAttendance> getHrmsEmployeeAttendances() {
		return this.hrmsEmployeeAttendances;
	}

	public void setHrmsEmployeeAttendances(Set<HrmsEmployeeAttendance> hrmsEmployeeAttendances) {
		this.hrmsEmployeeAttendances = hrmsEmployeeAttendances;
	}

}
