package org.packt.human.resource.portal.model.data;
// Generated 08 7, 15 10:09:21 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HrmsEmployeeProjects generated by hbm2java
 */
@Entity
@Table(name = "hrms_employee_projects", catalog = "hrms")
public class HrmsEmployeeProjects implements java.io.Serializable {

	private Integer id;
	private HrmsEmployeeDetails hrmsEmployeeDetails;
	private String projectHandled;
	private Date dateStarted;
	private Date dateEnded;
	private String status;

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "empId", nullable = false)
	public HrmsEmployeeDetails getHrmsEmployeeDetails() {
		return this.hrmsEmployeeDetails;
	}

	public void setHrmsEmployeeDetails(HrmsEmployeeDetails hrmsEmployeeDetails) {
		this.hrmsEmployeeDetails = hrmsEmployeeDetails;
	}

	@Column(name = "projectHandled", nullable = false, length = 100)
	public String getProjectHandled() {
		return this.projectHandled;
	}

	public void setProjectHandled(String projectHandled) {
		this.projectHandled = projectHandled;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateStarted", nullable = false, length = 10)
	public Date getDateStarted() {
		return this.dateStarted;
	}

	public void setDateStarted(Date dateStarted) {
		this.dateStarted = dateStarted;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateEnded", length = 10)
	public Date getDateEnded() {
		return this.dateEnded;
	}

	public void setDateEnded(Date dateEnded) {
		this.dateEnded = dateEnded;
	}

	@Column(name = "status", nullable = false, length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
