package org.packt.human.resource.portal.model.data;
// Generated 08 7, 15 10:09:21 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HrmsEmployeeAttendance generated by hbm2java
 */
@Entity
@Table(name = "hrms_employee_attendance", catalog = "hrms")
public class HrmsEmployeeAttendance implements java.io.Serializable {

	private Integer id;
	private HrmsEmployeeDetails hrmsEmployeeDetails;
	private Date timeIn;
	private Date timeOut;
	private String remarks;

	
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "empId", nullable = false)
	public HrmsEmployeeDetails getHrmsEmployeeDetails() {
		return this.hrmsEmployeeDetails;
	}

	public void setHrmsEmployeeDetails(HrmsEmployeeDetails hrmsEmployeeDetails) {
		this.hrmsEmployeeDetails = hrmsEmployeeDetails;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "timeIn", nullable = false, length = 10)
	public Date getTimeIn() {
		return this.timeIn;
	}

	public void setTimeIn(Date timeIn) {
		this.timeIn = timeIn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "timeOut", nullable = false, length = 10)
	public Date getTimeOut() {
		return this.timeOut;
	}

	public void setTimeOut(Date timeOut) {
		this.timeOut = timeOut;
	}

	@Column(name = "remarks", length = 50)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
