package org.packt.human.resource.portal.model.data;
// Generated 08 17, 15 2:36:29 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HrmsNews generated by hbm2java
 */
@Entity
@Table(name = "hrms_news", catalog = "hrms")
public class HrmsNews implements java.io.Serializable {

	private Integer id;
	private String description;
	private String summary;
	private String link;
	private String author;

	public HrmsNews() {
	}

	public HrmsNews(String description, String summary, String link, String author) {
		this.description = description;
		this.summary = summary;
		this.link = link;
		this.author = author;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "description", nullable = false, length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "summary", nullable = false)
	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	@Column(name = "link", nullable = false, length = 45)
	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	@Column(name = "author", nullable = false, length = 45)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

}
