package org.packt.human.resource.portal.model.data;
// Generated 08 7, 15 10:09:21 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HrmsEmployeeLeaves generated by hbm2java
 */
@Entity
@Table(name = "hrms_employee_leaves", catalog = "hrms")
public class HrmsEmployeeLeaves implements java.io.Serializable {

	private Integer id;
	private HrmsEmployeeDetails hrmsEmployeeDetails;
	private Leaves leaves;
	private Date startDate;
	private Date endDate;
	private double totalDays;

	
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "empId", nullable = false)
	public HrmsEmployeeDetails getHrmsEmployeeDetails() {
		return this.hrmsEmployeeDetails;
	}

	public void setHrmsEmployeeDetails(HrmsEmployeeDetails hrmsEmployeeDetails) {
		this.hrmsEmployeeDetails = hrmsEmployeeDetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "leaveId", nullable = false)
	public Leaves getLeaves() {
		return this.leaves;
	}

	public void setLeaves(Leaves leaves) {
		this.leaves = leaves;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "startDate", nullable = false, length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "endDate", nullable = false, length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "totalDays", nullable = false, precision = 22, scale = 0)
	public double getTotalDays() {
		return this.totalDays;
	}

	public void setTotalDays(double totalDays) {
		this.totalDays = totalDays;
	}

}
