package org.packt.human.resource.portal.model.data;
// Generated 08 7, 15 10:09:21 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * HrmsEmployeeTrainings generated by hbm2java
 */
@Entity
@Table(name = "hrms_employee_trainings", catalog = "hrms")
public class HrmsEmployeeTrainings implements java.io.Serializable {

	private Integer id;
	private HrmsEmployeeDetails hrmsEmployeeDetails;
	private String skills;
	private String training;
	private String projectReqt;
	private double bond;

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "empId", nullable = false)
	public HrmsEmployeeDetails getHrmsEmployeeDetails() {
		return this.hrmsEmployeeDetails;
	}

	public void setHrmsEmployeeDetails(HrmsEmployeeDetails hrmsEmployeeDetails) {
		this.hrmsEmployeeDetails = hrmsEmployeeDetails;
	}

	@Column(name = "skills", nullable = false)
	public String getSkills() {
		return this.skills;
	}

	public void setSkills(String skills) {
		this.skills = skills;
	}

	@Column(name = "training", nullable = false, length = 45)
	public String getTraining() {
		return this.training;
	}

	public void setTraining(String training) {
		this.training = training;
	}

	@Column(name = "projectReqt", nullable = false, length = 45)
	public String getProjectReqt() {
		return this.projectReqt;
	}

	public void setProjectReqt(String projectReqt) {
		this.projectReqt = projectReqt;
	}

	@Column(name = "bond", nullable = false, precision = 22, scale = 0)
	public double getBond() {
		return this.bond;
	}

	public void setBond(double bond) {
		this.bond = bond;
	}

}
