package org.packt.human.resource.portal.model.data;
// Generated 08 7, 15 10:09:21 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Positions generated by hbm2java
 */
@Entity
@Table(name = "positions", catalog = "hrms")
public class Positions implements java.io.Serializable {

	private int positionId;
	private String positionName;
	private Set<HrmsEmployeeDetails> hrmsEmployeeDetailses = new HashSet<HrmsEmployeeDetails>(0);


	@Id

	@Column(name = "positionId", unique = true, nullable = false)
	public int getPositionId() {
		return this.positionId;
	}

	public void setPositionId(int positionId) {
		this.positionId = positionId;
	}

	@Column(name = "positionName", nullable = false, length = 50)
	public String getPositionName() {
		return this.positionName;
	}

	public void setPositionName(String positionName) {
		this.positionName = positionName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "positions")
	public Set<HrmsEmployeeDetails> getHrmsEmployeeDetailses() {
		return this.hrmsEmployeeDetailses;
	}

	public void setHrmsEmployeeDetailses(Set<HrmsEmployeeDetails> hrmsEmployeeDetailses) {
		this.hrmsEmployeeDetailses = hrmsEmployeeDetailses;
	}

}
