package org.packt.erp.modules.model.data;
// Generated 12 18, 15 7:22:56 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Invoice generated by hbm2java
 */
@Entity
@Table(name = "invoice", catalog = "erp_receivable")
public class Invoice implements java.io.Serializable {

	private Integer id;
	private PaymentAp paymentAp;
	private Date date;
	private String custId;
	private String cid;
	private String catId;
	private InvoicedProducts invoicedProducts;

	public Invoice() {
	}

	public Invoice(Date date) {
		this.date = date;
	}

	public Invoice(PaymentAp paymentAp, Date date, String custId, String cid,
			String catId, InvoicedProducts invoicedProducts) {
		this.paymentAp = paymentAp;
		this.date = date;
		this.custId = custId;
		this.cid = cid;
		this.catId = catId;
		this.invoicedProducts = invoicedProducts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pid")
	public PaymentAp getPaymentAp() {
		return this.paymentAp;
	}

	public void setPaymentAp(PaymentAp paymentAp) {
		this.paymentAp = paymentAp;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "custId", length = 45)
	public String getCustId() {
		return this.custId;
	}

	public void setCustId(String custId) {
		this.custId = custId;
	}

	@Column(name = "cid", length = 45)
	public String getCid() {
		return this.cid;
	}

	public void setCid(String cid) {
		this.cid = cid;
	}

	@Column(name = "catId", length = 45)
	public String getCatId() {
		return this.catId;
	}

	public void setCatId(String catId) {
		this.catId = catId;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "invoice")
	public InvoicedProducts getInvoicedProducts() {
		return this.invoicedProducts;
	}

	public void setInvoicedProducts(InvoicedProducts invoicedProducts) {
		this.invoicedProducts = invoicedProducts;
	}

}
