package org.packt.academic.student.portal.model.data;
// Generated 03 14, 16 11:36:05 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tbladminuser generated by hbm2java
 */
@Entity
@Table(name = "tbladminuser", catalog = "smp")
public class Tbladminuser implements java.io.Serializable {

	private String username;
	private String password;

	public Tbladminuser() {
	}

	public Tbladminuser(String username, String password) {
		this.username = username;
		this.password = password;
	}

	@Id
	@Column(name = "username", unique = true, nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
