package org.packt.academic.student.portal.model.data;
// Generated 03 14, 16 11:36:05 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tblfaculty generated by hbm2java
 */
@Entity
@Table(name = "tblfaculty", catalog = "smp")
public class Tblfaculty implements java.io.Serializable {

	private int facultyId;
	private Tbldepartment tbldepartment;
	private String firstName;
	private String lastName;
	private String middleName;
	private String username;

	public Tblfaculty() {
	}

	public Tblfaculty(int facultyId, Tbldepartment tbldepartment,
			String firstName, String lastName, String middleName,
			String username) {
		this.facultyId = facultyId;
		this.tbldepartment = tbldepartment;
		this.firstName = firstName;
		this.lastName = lastName;
		this.middleName = middleName;
		this.username = username;
	}

	@Id
	@Column(name = "facultyId", unique = true, nullable = false)
	public int getFacultyId() {
		return this.facultyId;
	}

	public void setFacultyId(int facultyId) {
		this.facultyId = facultyId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "departmentId", nullable = false)
	public Tbldepartment getTbldepartment() {
		return this.tbldepartment;
	}

	public void setTbldepartment(Tbldepartment tbldepartment) {
		this.tbldepartment = tbldepartment;
	}

	@Column(name = "firstName", nullable = false, length = 50)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "lastName", nullable = false, length = 50)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "middleName", nullable = false, length = 50)
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "username", nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

}
