package org.packt.academic.student.portal.model.data;

// Generated 10 3, 15 11:23:41 AM by Hibernate Tools 4.3.1


/**
 * Status generated by hbm2java
 */
public class Status  {

	private int status;
	private String label;
	

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	
}
