package org.packt.academic.student.portal.model.data;

// Generated 10 3, 15 11:23:41 AM by Hibernate Tools 4.3.1


/**
 * Tblcourses generated by hbm2java
 */
public class Tblcourses  {

	private String courseCode;
	private int deptId;
	private String courseName;
	private int courseUnit;
	
	
	public String getCourseCode() {
		return this.courseCode;
	}

	public void setCourseCode(String courseCode) {
		this.courseCode = courseCode;
	}

	public int getDeptId() {
		return deptId;
	}

	public void setDeptId(int deptId) {
		this.deptId = deptId;
	}

	public String getCourseName() {
		return this.courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	public int getCourseUnit() {
		return this.courseUnit;
	}

	public void setCourseUnit(int courseUnit) {
		this.courseUnit = courseUnit;
	}

	

}
