package org.packt.academic.student.portal.model.data;

// Generated 10 3, 15 11:23:41 AM by Hibernate Tools 4.3.1

/**
 * Tblgpa generated by hbm2java
 */
public class Tblgpa  {

	private int studentId;
	private String gpaCalculated;

	

	public int getStudentId() {
		return this.studentId;
	}

	public void setStudentId(int studentId) {
		this.studentId = studentId;
	}

	
	public String getGpaCalculated() {
		return this.gpaCalculated;
	}

	public void setGpaCalculated(String gpaCalculated) {
		this.gpaCalculated = gpaCalculated;
	}

}
