package org.packt.academic.student.portal.model.data;

// Generated 03 9, 16 11:21:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tblstudents generated by hbm2java
 */
public class Tblstudents implements java.io.Serializable {

	private Integer studentId;
	private Status status;
	private Semester semester;
	private Level level;
	private String firstName;
	private String lastName;
	private String middleName;
	private String gender;
	private Date birthDate;
	private String degree;
	private String address;
	private String mobile;
	private String email;
	private String username;
	private Tblgpa tblgpa;
	private Set tblstudentgradeses = new HashSet(0);

	public Tblstudents() {
	}

	public Tblstudents(Status status, Semester semester, Level level,
			String firstName, String lastName, String middleName,
			String gender, Date birthDate, String degree, String address,
			String mobile, String email, String username) {
		this.status = status;
		this.semester = semester;
		this.level = level;
		this.firstName = firstName;
		this.lastName = lastName;
		this.middleName = middleName;
		this.gender = gender;
		this.birthDate = birthDate;
		this.degree = degree;
		this.address = address;
		this.mobile = mobile;
		this.email = email;
		this.username = username;
	}

	public Tblstudents(Status status, Semester semester, Level level,
			String firstName, String lastName, String middleName,
			String gender, Date birthDate, String degree, String address,
			String mobile, String email, String username, Tblgpa tblgpa,
			Set tblstudentgradeses) {
		this.status = status;
		this.semester = semester;
		this.level = level;
		this.firstName = firstName;
		this.lastName = lastName;
		this.middleName = middleName;
		this.gender = gender;
		this.birthDate = birthDate;
		this.degree = degree;
		this.address = address;
		this.mobile = mobile;
		this.email = email;
		this.username = username;
		this.tblgpa = tblgpa;
		this.tblstudentgradeses = tblstudentgradeses;
	}

	public Integer getStudentId() {
		return this.studentId;
	}

	public void setStudentId(Integer studentId) {
		this.studentId = studentId;
	}

	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	public Semester getSemester() {
		return this.semester;
	}

	public void setSemester(Semester semester) {
		this.semester = semester;
	}

	public Level getLevel() {
		return this.level;
	}

	public void setLevel(Level level) {
		this.level = level;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	public String getDegree() {
		return this.degree;
	}

	public void setDegree(String degree) {
		this.degree = degree;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Tblgpa getTblgpa() {
		return this.tblgpa;
	}

	public void setTblgpa(Tblgpa tblgpa) {
		this.tblgpa = tblgpa;
	}

	public Set getTblstudentgradeses() {
		return this.tblstudentgradeses;
	}

	public void setTblstudentgradeses(Set tblstudentgradeses) {
		this.tblstudentgradeses = tblstudentgradeses;
	}

}
