package org.packt.academic.student.portal.model.data;

// Generated 03 12, 16 1:32:12 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Proxy;

/**
 * Tblcourses generated by hbm2java
 */
@Entity
@Proxy(lazy=false)
@Table(name = "tblcourses", catalog = "smp")
public class Tblcourses implements java.io.Serializable {

	private String courseCode;
	private Tbldepartment tbldepartment;
	private String courseName;
	private int courseUnit;
	private Set<Tblstudentgrades> tblstudentgradeses = new HashSet<Tblstudentgrades>(
			0);

	public Tblcourses() {
	}

	public Tblcourses(String courseCode, Tbldepartment tbldepartment,
			String courseName, int courseUnit) {
		this.courseCode = courseCode;
		this.tbldepartment = tbldepartment;
		this.courseName = courseName;
		this.courseUnit = courseUnit;
	}

	public Tblcourses(String courseCode, Tbldepartment tbldepartment,
			String courseName, int courseUnit,
			Set<Tblstudentgrades> tblstudentgradeses) {
		this.courseCode = courseCode;
		this.tbldepartment = tbldepartment;
		this.courseName = courseName;
		this.courseUnit = courseUnit;
		this.tblstudentgradeses = tblstudentgradeses;
	}

	@Id
	@Column(name = "courseCode", unique = true, nullable = false, length = 15)
	public String getCourseCode() {
		return this.courseCode;
	}

	public void setCourseCode(String courseCode) {
		this.courseCode = courseCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "departmentID", nullable = false)
	public Tbldepartment getTbldepartment() {
		return this.tbldepartment;
	}

	public void setTbldepartment(Tbldepartment tbldepartment) {
		this.tbldepartment = tbldepartment;
	}

	@Column(name = "courseName", nullable = false, length = 50)
	public String getCourseName() {
		return this.courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	@Column(name = "courseUnit", nullable = false)
	public int getCourseUnit() {
		return this.courseUnit;
	}

	public void setCourseUnit(int courseUnit) {
		this.courseUnit = courseUnit;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblcourses")
	public Set<Tblstudentgrades> getTblstudentgradeses() {
		return this.tblstudentgradeses;
	}

	public void setTblstudentgradeses(Set<Tblstudentgrades> tblstudentgradeses) {
		this.tblstudentgradeses = tblstudentgradeses;
	}

}
