package org.packt.academic.student.portal.model.data;

// Generated 03 12, 16 1:32:12 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tbldepartment generated by hbm2java
 */
@Entity
@Table(name = "tbldepartment", catalog = "smp")
public class Tbldepartment implements java.io.Serializable {

	private int departmentId;
	private String departmentName;
	private Set<Tblcourses> tblcourseses = new HashSet<Tblcourses>(0);
	private Set<Tblfaculty> tblfaculties = new HashSet<Tblfaculty>(0);

	public Tbldepartment() {
	}

	public Tbldepartment(int departmentId, String departmentName) {
		this.departmentId = departmentId;
		this.departmentName = departmentName;
	}

	public Tbldepartment(int departmentId, String departmentName,
			Set<Tblcourses> tblcourseses, Set<Tblfaculty> tblfaculties) {
		this.departmentId = departmentId;
		this.departmentName = departmentName;
		this.tblcourseses = tblcourseses;
		this.tblfaculties = tblfaculties;
	}

	@Id
	@Column(name = "departmentID", unique = true, nullable = false)
	public int getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(int departmentId) {
		this.departmentId = departmentId;
	}

	@Column(name = "departmentName", nullable = false, length = 50)
	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbldepartment")
	public Set<Tblcourses> getTblcourseses() {
		return this.tblcourseses;
	}

	public void setTblcourseses(Set<Tblcourses> tblcourseses) {
		this.tblcourseses = tblcourseses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbldepartment")
	public Set<Tblfaculty> getTblfaculties() {
		return this.tblfaculties;
	}

	public void setTblfaculties(Set<Tblfaculty> tblfaculties) {
		this.tblfaculties = tblfaculties;
	}

}
