package org.packt.academic.student.portal.model.data;

// Generated 03 12, 16 1:32:12 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tblfacultyuser generated by hbm2java
 */
@Entity
@Table(name = "tblfacultyuser", catalog = "smp")
public class Tblfacultyuser implements java.io.Serializable {

	private String username;
	private String password;

	public Tblfacultyuser() {
	}

	public Tblfacultyuser(String username, String password) {
		this.username = username;
		this.password = password;
	}

	@Id
	@Column(name = "username", unique = true, nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
