package org.packt.academic.student.portal.model.data;

// Generated 03 12, 16 1:32:12 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Proxy;

/**
 * Tblstudentgrades generated by hbm2java
 */
@Entity
@Proxy(lazy=false)
@Table(name = "tblstudentgrades", catalog = "smp")
public class Tblstudentgrades implements java.io.Serializable {

	private Integer id;
	private Tblcourses tblcourses;
	private Tblstudents tblstudents;
	private double grade;
	private int semester;
	private int level;
	private int facultyId;

	public Tblstudentgrades() {
	}

	public Tblstudentgrades(Tblcourses tblcourses, Tblstudents tblstudents,
			double grade, int semester, int level, int facultyId) {
		this.tblcourses = tblcourses;
		this.tblstudents = tblstudents;
		this.grade = grade;
		this.semester = semester;
		this.level = level;
		this.facultyId = facultyId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "courseCode", nullable = false)
	public Tblcourses getTblcourses() {
		return this.tblcourses;
	}

	public void setTblcourses(Tblcourses tblcourses) {
		this.tblcourses = tblcourses;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "studentID", nullable = false)
	public Tblstudents getTblstudents() {
		return this.tblstudents;
	}

	public void setTblstudents(Tblstudents tblstudents) {
		this.tblstudents = tblstudents;
	}

	@Column(name = "grade", nullable = false, precision = 22, scale = 0)
	public double getGrade() {
		return this.grade;
	}

	public void setGrade(double grade) {
		this.grade = grade;
	}

	@Column(name = "semester", nullable = false)
	public int getSemester() {
		return this.semester;
	}

	public void setSemester(int semester) {
		this.semester = semester;
	}

	@Column(name = "level", nullable = false)
	public int getLevel() {
		return this.level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	@Column(name = "facultyId", nullable = false)
	public int getFacultyId() {
		return this.facultyId;
	}

	public void setFacultyId(int facultyId) {
		this.facultyId = facultyId;
	}

}
