// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.packt.hotel.portal.jpa.data;

import org.packt.hotel.portal.jpa.data.HmsRoomType;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect HmsRoomType_Roo_Configurable {
    
    declare @type: HmsRoomType: @Configurable;
    
}
