/*
 *  Author: Sherwin John Caleja-Tragura
 *  Version: 1.0
 */
package org.packt.feedback.portal.model.data;
// Generated 08 28, 15 12:01:01 AM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CfsTopic generated by hbm2java
 */
@Entity
@Table(name = "cfs_topic", catalog = "cfs")
public class CfsTopic implements java.io.Serializable {

	private Integer id;
	private String title;
	private String description;
	private Date date;
	private Set<CfsFeedback> cfsFeedbacks = new HashSet<CfsFeedback>(0);

	public CfsTopic() {
	}

	public CfsTopic(String title, Date date) {
		this.title = title;
		this.date = date;
	}

	public CfsTopic(String title, String description, Date date, Set<CfsFeedback> cfsFeedbacks) {
		this.title = title;
		this.description = description;
		this.date = date;
		this.cfsFeedbacks = cfsFeedbacks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false, length = 200)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cfsTopic")
	public Set<CfsFeedback> getCfsFeedbacks() {
		return this.cfsFeedbacks;
	}

	public void setCfsFeedbacks(Set<CfsFeedback> cfsFeedbacks) {
		this.cfsFeedbacks = cfsFeedbacks;
	}

}
